version: '2.1'
# Prometheus demonstration of the autopilot pattern

services:
  prometheus:
      image: autopilotpattern/prometheus:${TAG:-latest}
      mem_limit: 1g
      # Joyent recommends setting instances to always restart on Triton
      restart: always
      labels:
        - triton.cns.services=prometheus
        # This label sets the CNS name, Triton's automatic DNS
        # Learn more at https://docs.joyent.com/public-cloud/network/cns
        - com.joyent.package=g4-highcpu-1G
        # This label selects the proper Joyent resource package 
        # https://www.joyent.com/blog/optimizing-docker-on-triton#ram-cpu-and-disk-resources-for-your-containers
      network_mode: bridge
      ports:
        # You may not want these port declarations for production. Without them, Prometheus will only 
        # listen on the private network. This will also result in a public redis CNS record being created, 
        # in the triton.zone domain.
        - 9090
      env_file: _env


  # Consul acts as our service catalog and is used to coordinate global state among 
  # our Redis containers
  consul:
    image: autopilotpattern/consul:0.7.2-r0.8
    command: >
      /usr/local/bin/containerpilot
      /bin/consul agent -server
        -bootstrap-expect 1
        -config-dir=/etc/consul
        -ui-dir /ui
    # Change "-bootstrap" to "-bootstrap-expect 3", then scale to 3 or more to
    # turn this into an HA Consul raft.
    restart: always
    mem_limit: 128m
    ports:
      # As above, this port delcarations should not be made for production.
      - 8500
    labels:
      - triton.cns.services=redis-consul
    network_mode: bridge
